import jsPDF from "jspdf";
import type { Benefit } from "./mock-data";

interface ExportData {
  tier: string;
  tierDisplay: string;
  issuer: string;
  benefits: Benefit[];
  summaries: Record<string, string>;
}

export function exportBenefitsToPDF(data: ExportData) {
  const { tier, tierDisplay, issuer, benefits, summaries } = data;
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let yPosition = 20;

  // Helper to add new page if needed
  const checkNewPage = (neededSpace: number) => {
    if (yPosition + neededSpace > 270) {
      doc.addPage();
      yPosition = 20;
    }
  };

  // Title
  doc.setFontSize(24);
  doc.setTextColor(26, 54, 126); // Visa blue
  doc.text("Visa Card Benefits Summary", margin, yPosition);
  yPosition += 15;

  // Card Info
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Card: ${tierDisplay}`, margin, yPosition);
  yPosition += 7;
  doc.text(`Issuer: ${issuer}`, margin, yPosition);
  yPosition += 7;
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPosition);
  yPosition += 15;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  // Group benefits by category
  const grouped = benefits.reduce((acc, benefit) => {
    if (!acc[benefit.category]) {
      acc[benefit.category] = [];
    }
    acc[benefit.category].push(benefit);
    return acc;
  }, {} as Record<string, Benefit[]>);

  // Category icons (for display names)
  const categoryIcons: Record<string, string> = {
    Travel: "✈️",
    Shopping: "🛍️",
    Lifestyle: "🎯",
  };

  // Benefits by category
  Object.entries(grouped).forEach(([category, categoryBenefits]) => {
    checkNewPage(30);
    
    // Category header
    doc.setFontSize(16);
    doc.setTextColor(26, 54, 126);
    const icon = categoryIcons[category] || "•";
    doc.text(`${icon} ${category}`, margin, yPosition);
    yPosition += 10;

    categoryBenefits.forEach((benefit) => {
      checkNewPage(40);

      // Benefit name
      doc.setFontSize(12);
      doc.setTextColor(40);
      doc.text(`• ${benefit.name}`, margin + 5, yPosition);
      yPosition += 7;

      // AI Summary
      const summary = summaries[benefit.id];
      if (summary) {
        doc.setFontSize(10);
        doc.setTextColor(80);
        const summaryLines = doc.splitTextToSize(`Summary: ${summary}`, contentWidth - 10);
        summaryLines.forEach((line: string) => {
          checkNewPage(7);
          doc.text(line, margin + 10, yPosition);
          yPosition += 5;
        });
      }

      yPosition += 5;
    });

    yPosition += 5;
  });

  // Footer
  checkNewPage(20);
  yPosition += 10;
  doc.setDrawColor(200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by VisaBenefit.AI - Your Smart Card Benefit Co-Pilot", margin, yPosition);
  yPosition += 5;
  doc.text("This document is for informational purposes. Please refer to official terms for complete details.", margin, yPosition);

  // Save
  const fileName = `visa-benefits-${tier}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}
